language: ruby
rvm:
  - 2.4.9
  - 2.5.6
  - 2.6.5
gemfile:
  - ci/Gemfile-rails-4-2
  - ci/Gemfile-rails-5-0
  - ci/Gemfile-rails-5-1
  - ci/Gemfile-rails-5-2
  - ci/Gemfile-rails-6-0
matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: ci/Gemfile-rails-6-0
before_install: gem update bundler
sudo: false
