os: linux
dist: xenial
language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0
gemfile:
  - ci/Gemfile-rails-4-2
  - ci/Gemfile-rails-5-0
  - ci/Gemfile-rails-5-1
  - ci/Gemfile-rails-5-2
  - ci/Gemfile-rails-6-0
  - ci/Gemfile-rails-6-1
matrix:
  exclude:
    - rvm: 2.7.2
      gemfile: ci/Gemfile-rails-4-2
    - rvm: 3.0.0
      gemfile: ci/Gemfile-rails-4-2
    - rvm: 3.0.0
      gemfile: ci/Gemfile-rails-5-0
    - rvm: 3.0.0
      gemfile: ci/Gemfile-rails-5-1
    - rvm: 3.0.0
      gemfile: ci/Gemfile-rails-5-2
before_install: gem update bundler
